id: P9F7574A8
initial_creation_type: ocr
source_metadata:
  volumes:
    438a693677b7410ea8574bc68f335654:
      base_file: v055.txt
      image_group_id: I1PD95900
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་མ་བསྡུས་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1470
      volume_number: 55
